title: Abdelrahman Mahmoud
logo: /asset/img/WhatsApp Image 2024-10-28 at 11.07.30.jpeg
description: ERP Project Leader | Tech Innovator | Entrepreneurship Mentor
show_downloads: true
theme: jekyll-theme-minimal
